version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    networks:
      - my-network

  app:
    build: ./app
    container_name: python-app
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:

